language: go
go:
- '1.12'
env:
  global:
  - GO111MODULE=on
  - PROJECT=go-infrabin
  - secure: XUggoTKUhNyaUrJ/bum3y0092of3zJ/MXo4Dedzb9zAxa3mERsNcJklJz8rLECp95QkZxXeJRhX0q8IRJWXCUEdLJ6U79oqYekVSkqcpMO0OzKjkJPKw6E6jWO6gCHoKOpUE24Or6VY5ddv8ZzT9qK5ZxR8s/GPUo9s4f/vVHa41AY/nBHIfTpuciu3rIhXDuZtU8u8JU1ZzOoO9HlBCWeJ11QJJVYKGaPTzLBoETvx8jz/j9ju3EluNmJ6xtXAIIetl9vHYi+xgJpd/YfCRTUVg5S3dXUGVfYtaQ6XvS/6O3uhl2Jpw1/S+Ilx0L0NQPOUnOT9EQZwimnTfjU6+6GjWLlkOuiDGF5I5l97ih7jJQ3ljG2R05nIapPGYThMgbA5aBbKVwpxLd9soI2dLtqKiEnzC9omqy1LQCwCm8AmgxlMT2Fjxm5KiqlKgyMppNQmS3oKG0PWj8k70ZNbEaCCmiygY2ADyoExU9PCEWFxl6mqXT52DlbiDLR798fe4M26Y0kS7NbM80VgePBOZYWVlMifHgBjrxyOkkdRXDUu6QMnY6rV8al77V8NndYUgUvXhzEF1/TheKrqC/KVpY3H0TZALSmD1Fua9Z2QGkrAn9Uc8t3XELCWcMpIbugTMn6LTC17uQrDDeufQf+SVfJ7wFBZ8rg3DIXqMQQsjJKI=
  - secure: us7EitVIW5hH4lVKAkWywDPBKkjJQKIYhbIzkElng6WBoTCo7AVIEatX4Y7WbQo3AlrNkvqjlH6pg4eKFEgiTPjqSzdEtyz0VJxkboFURZJ4jRPIqfEC6ZctpfD3NY34OIa8efF9TGBYG4y7DtKXJjqfXktZvL18AKfF9m278st7triR/pKs/7yW5Fp3ufgENGcvLH+Zbfpi5b1pcCU2+3+0ZZKWwH3SvvDwihmjxg7/YpY+id6mSZnAvpqM8bE+sI3wlXyFj2r9tgUv/9kqh1V2+k/F8aQN5f8TnJqQq960HcDA8Lq/45aHS8BfphevaDR92ryFcMAoshtbGDRlB5zrQUQ4oosGqxIT8fO4lBXRcnZaO32jR2eGIv8rHqBlwN8WrzDC4609AkGSM7yX/kNRu3Rb2t8M5SpkGl5r3a1g5Y1LWiNT++LEnYYLz6R/iBfU9+1bD8kLKBYPwAma0qaIbRBMdy+s7bvh4yn13ShlCflmGh2XqG2JIBlK6LnyhAkwApIuHoBSkQMBqhHtb8emfqcACR9jxuQVsXEB+v4/yxTkwWkmLhG+LBeluv971/o2v0Sms0pE58IMEmB9Fn7UfANXa4nKLcZ0tCBO6Sgui1jDkP71Q3hAU6jdWpT3xOLIg5i8xaRjSWXQ9MQqW/hH07pNWW7+te5K+DblDc4=
  - secure: UI+QVfKNMBTYCPuuYN6fnAlAJ/kB5pMzH3Rk+xPxDRDgLSPnuIuU39H38XzU/O5WPi59VKtxuTxK3jO41u5uscs6zAFUwhk7DMk1zp8iDPpV5bAOqad2OGrXjLiV8/zg5N8I411V6HQymBJ9EkDsuTmSQ/3hFOlOaf1hjsPuxpesWZj+OVv2sFJk4NeqaxIAZLES77cmU2NbDA0oO5AZmTpXPe5Gdr91iUUp+glQV+MB1L0TyYixjtLYyo63uMI7lBEUwS8yqCqFlji9iG203gWickPUZETsRuWQK8ns4FYFlC0sx3nNpTKOG2fgm/jlBxcKP+gjyPdRsR5axhhVqytvDlvbVuEb15mvgEpv5YuqRBJ36HsmKivWC/IWfOw0wpWQjJRBoGl6TtdlevtHmBbwBFaq64Ei4rV23NejtjaxeY2OnKnnoIdCxAWi8dIc0QXNaiD2fPTVOAhuAz0POTKtuxr+BbGTTrV6fnRcIzyIcyxEG8+padUsl+Ij/oRfQal1SascUZiTspY3XQKnsPweGxQJPbGIs3yezNzi6A2yRSp/4DHsVh0uG1jxZgt3UWcoAQgtVyABN0W4Z4lBwjnG54/7TuUVe2fMaM7ek/exJqcgijQAJ5N16ulhYGizX9Px8vegJm0KLW1hejmBgg5ly+xBjUo8fQstwfFCb3M=
  - secure: diu/ehu+XaPky7rLqPR82a9Wp1LrEABfwkzLGkDqOP4/yunZ0/0pD6oZ6EpTkeLVQe+JDf1+1C9m7JN9eYxxn08VG9yKyjVegQhJOXsYf22A64N2kBUC1jTn8B19YmHXlMVdBaynTbDC+gduqyRxkPmhWCjbYOTudYua0vYxF2fo0Fw9dMhiOQ8OF3wauCzPWm81BveWUzREZ+kBLJAPsY8nNEWyVcngfikIJlguTrtXb759bPfKEjXuuGmNx8P0IcfyoaC9DcBmVwkECGBEHfUPN2z9IcLLCbb8RnxI+TARTZTm2QDNJoWM2dK4V4wTfM3hl24imWuGzh1wHA8ozb5jZv1A1Dc01g/g0OJ27dB2jgkOtxBj9fPdrf/8y4DXddzbQlJ3xt9jO/v3aeKpZvr598nxWgxmQ1rN3QP0HzwR6sN6yERSImHfEtGliMezl6ozui0Lne2x9mvpRZgoXHk3QwHxD3xLlmgZkVo0MErVBIf+jnmBz5GT6qvDFA1PBqf58XapJJNS5mDSC96M7yJ1wqvBEq+2R2WqQKiXQVX0bjS7EXp1BsHP2WSTvtUY1E7mHLSMr+XZlDrXqZA+bXvHNSHuGrliR/iVJBvnEWFYAqVSXxLhOHkwVYlq7+38418Lc5P2qoRUL5iT38bErSClDKUY9OmJ0G/BNvaQUE8=
install: make dep-ci
cache:
  directories:
  - "$GOPATH/pkg/mod"
jobs:
  include:
  - stage: Compile
    name: Compile Packages and Dependencies
    script: make build
  - stage: Tests
    name: Unit Tests
    script: make test-ci
  - stage: Code Quality
    name: Code Quality Analysis
    before_script:
    - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh
      | bash -s -- -b $GOPATH/bin v1.12.5
    script: golangci-lint run
  - stage: Release
    name: Release Binaries
    script: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin
    deploy:
    - provider: script
      skip_cleanup: true
      script: curl -sL https://git.io/goreleaser | bash
      on:
        tags: true
        condition: "$TRAVIS_OS_NAME = linux"
